### ISSUE TITLE
[BUG] Orderbook for a Private Market includes ALL Orders

### ISSUE THREAD

**Issue by darkfishy** [flexemarkets/fm-issues#38] opened 2019-07-15 04:29 UTC
Fetching available orders for a private market using `https://fm-data.herokuapp.com/api/orders/search/orders-available?marketId={market_id}` also includes orders for which the currently authenticated used is neither the owner nor the target.

This results in incorrect reasoning when checking for whether an order is 'mine' or was sent to 'me'.

**Comment by JanStureNielsen** [comment] 2019-07-18 00:14
Duplicate of #37.

**Closed as completed by JanStureNielsen** 2019-07-18 00:14 UTC
Labels: bug
